version: '3.8'
services:
  backend:
    build: ./backend/auth-service
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend/auth-service:/app

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
